name: Daily Joke
on:
  schedule:
    - cron: '50 18,19,20 * * *'
  workflow_dispatch: 

jobs:
  run-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install discord.py aiohttp
      - name: Run script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python3 joke.py
